# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 814)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(40, 10, 941, 731))
        self.stackedWidget.setAutoFillBackground(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.labelTitel = QtWidgets.QLabel(self.page_0)
        self.labelTitel.setGeometry(QtCore.QRect(20, 10, 921, 541))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTitel.setFont(font)
        self.labelTitel.setAutoFillBackground(True)
        self.labelTitel.setObjectName("labelTitel")
        self.btnBegin = QtWidgets.QPushButton(self.page_0)
        self.btnBegin.setGeometry(QtCore.QRect(300, 570, 361, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 37, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.btnBegin.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.btnBegin.setFont(font)
        self.btnBegin.setMouseTracking(True)
        self.btnBegin.setObjectName("btnBegin")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label = QtWidgets.QLabel(self.page_1)
        self.label.setGeometry(QtCore.QRect(210, 310, 461, 141))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(210, 310, 431, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.labelVideoNum_1 = QtWidgets.QLabel(self.page_3)
        self.labelVideoNum_1.setGeometry(QtCore.QRect(10, 10, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.labelVideoNum_1.setFont(font)
        self.labelVideoNum_1.setObjectName("labelVideoNum_1")
        self.videoPlayer = QVideoWidget(self.page_3)
        self.videoPlayer.setGeometry(QtCore.QRect(10, 60, 911, 651))
        self.videoPlayer.setAutoFillBackground(True)
        self.videoPlayer.setObjectName("videoPlayer")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.labelVideoNum_2 = QtWidgets.QLabel(self.page_4)
        self.labelVideoNum_2.setGeometry(QtCore.QRect(10, 10, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.labelVideoNum_2.setFont(font)
        self.labelVideoNum_2.setObjectName("labelVideoNum_2")
        self.label_3 = QtWidgets.QLabel(self.page_4)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBoxEmotion1 = QtWidgets.QGroupBox(self.page_4)
        self.groupBoxEmotion1.setGeometry(QtCore.QRect(10, 190, 901, 131))
        self.groupBoxEmotion1.setTitle("")
        self.groupBoxEmotion1.setObjectName("groupBoxEmotion1")
        self.checkBoxHappy = QtWidgets.QCheckBox(self.groupBoxEmotion1)
        self.checkBoxHappy.setGeometry(QtCore.QRect(20, 20, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBoxHappy.setFont(font)
        self.checkBoxHappy.setObjectName("checkBoxHappy")
        self.checkBoxAngry = QtWidgets.QCheckBox(self.groupBoxEmotion1)
        self.checkBoxAngry.setGeometry(QtCore.QRect(20, 70, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBoxAngry.setFont(font)
        self.checkBoxAngry.setObjectName("checkBoxAngry")
        self.checkBoxSad = QtWidgets.QCheckBox(self.groupBoxEmotion1)
        self.checkBoxSad.setGeometry(QtCore.QRect(160, 20, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBoxSad.setFont(font)
        self.checkBoxSad.setObjectName("checkBoxSad")
        self.checkBoxFear = QtWidgets.QCheckBox(self.groupBoxEmotion1)
        self.checkBoxFear.setGeometry(QtCore.QRect(160, 70, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBoxFear.setFont(font)
        self.checkBoxFear.setObjectName("checkBoxFear")
        self.checkBoxDisgust = QtWidgets.QCheckBox(self.groupBoxEmotion1)
        self.checkBoxDisgust.setGeometry(QtCore.QRect(290, 70, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBoxDisgust.setFont(font)
        self.checkBoxDisgust.setObjectName("checkBoxDisgust")
        self.checkBoxSuprised = QtWidgets.QCheckBox(self.groupBoxEmotion1)
        self.checkBoxSuprised.setGeometry(QtCore.QRect(290, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBoxSuprised.setFont(font)
        self.checkBoxSuprised.setObjectName("checkBoxSuprised")
        self.checkBoxExcited = QtWidgets.QCheckBox(self.groupBoxEmotion1)
        self.checkBoxExcited.setGeometry(QtCore.QRect(460, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBoxExcited.setFont(font)
        self.checkBoxExcited.setObjectName("checkBoxExcited")
        self.btnNext = QtWidgets.QPushButton(self.page_4)
        self.btnNext.setGeometry(QtCore.QRect(790, 650, 141, 71))
        self.btnNext.setObjectName("btnNext")
        self.label_6 = QtWidgets.QLabel(self.page_4)
        self.label_6.setGeometry(QtCore.QRect(510, 150, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.btnNext_2 = QtWidgets.QPushButton(self.page_5)
        self.btnNext_2.setGeometry(QtCore.QRect(790, 650, 141, 71))
        self.btnNext_2.setObjectName("btnNext_2")
        self.groupBox = QtWidgets.QGroupBox(self.page_5)
        self.groupBox.setGeometry(QtCore.QRect(10, 140, 971, 91))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButtonQ1A = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonQ1A.setGeometry(QtCore.QRect(10, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonQ1A.setFont(font)
        self.radioButtonQ1A.setObjectName("radioButtonQ1A")
        self.radioButtonQ1B = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonQ1B.setGeometry(QtCore.QRect(240, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonQ1B.setFont(font)
        self.radioButtonQ1B.setObjectName("radioButtonQ1B")
        self.radioButtonQ1C = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonQ1C.setGeometry(QtCore.QRect(470, 30, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonQ1C.setFont(font)
        self.radioButtonQ1C.setObjectName("radioButtonQ1C")
        self.radioButtonQ1D = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonQ1D.setGeometry(QtCore.QRect(720, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonQ1D.setFont(font)
        self.radioButtonQ1D.setObjectName("radioButtonQ1D")
        self.labelVideoNum_3 = QtWidgets.QLabel(self.page_5)
        self.labelVideoNum_3.setGeometry(QtCore.QRect(10, 10, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.labelVideoNum_3.setFont(font)
        self.labelVideoNum_3.setObjectName("labelVideoNum_3")
        self.label_5 = QtWidgets.QLabel(self.page_5)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_q1 = QtWidgets.QLabel(self.page_5)
        self.label_q1.setGeometry(QtCore.QRect(10, 100, 901, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_q1.setFont(font)
        self.label_q1.setObjectName("label_q1")
        self.label_7 = QtWidgets.QLabel(self.page_5)
        self.label_7.setGeometry(QtCore.QRect(10, 230, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_q2 = QtWidgets.QLabel(self.page_5)
        self.label_q2.setGeometry(QtCore.QRect(10, 270, 901, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_q2.setFont(font)
        self.label_q2.setObjectName("label_q2")
        self.groupBoxEmotion1_3 = QtWidgets.QGroupBox(self.page_5)
        self.groupBoxEmotion1_3.setGeometry(QtCore.QRect(10, 310, 951, 91))
        self.groupBoxEmotion1_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBoxEmotion1_3.setTitle("")
        self.groupBoxEmotion1_3.setObjectName("groupBoxEmotion1_3")
        self.radioButtonQ2A = QtWidgets.QRadioButton(self.groupBoxEmotion1_3)
        self.radioButtonQ2A.setGeometry(QtCore.QRect(10, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonQ2A.setFont(font)
        self.radioButtonQ2A.setObjectName("radioButtonQ2A")
        self.radioButtonQ2B = QtWidgets.QRadioButton(self.groupBoxEmotion1_3)
        self.radioButtonQ2B.setGeometry(QtCore.QRect(240, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonQ2B.setFont(font)
        self.radioButtonQ2B.setObjectName("radioButtonQ2B")
        self.radioButtonQ2C = QtWidgets.QRadioButton(self.groupBoxEmotion1_3)
        self.radioButtonQ2C.setGeometry(QtCore.QRect(470, 30, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonQ2C.setFont(font)
        self.radioButtonQ2C.setObjectName("radioButtonQ2C")
        self.radioButtonQ2D = QtWidgets.QRadioButton(self.groupBoxEmotion1_3)
        self.radioButtonQ2D.setGeometry(QtCore.QRect(720, 30, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonQ2D.setFont(font)
        self.radioButtonQ2D.setObjectName("radioButtonQ2D")
        self.label_9 = QtWidgets.QLabel(self.page_5)
        self.label_9.setGeometry(QtCore.QRect(10, 400, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_q3 = QtWidgets.QLabel(self.page_5)
        self.label_q3.setGeometry(QtCore.QRect(10, 440, 901, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_q3.setFont(font)
        self.label_q3.setObjectName("label_q3")
        self.groupBoxEmotion1_4 = QtWidgets.QGroupBox(self.page_5)
        self.groupBoxEmotion1_4.setGeometry(QtCore.QRect(10, 480, 951, 91))
        self.groupBoxEmotion1_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBoxEmotion1_4.setTitle("")
        self.groupBoxEmotion1_4.setObjectName("groupBoxEmotion1_4")
        self.radioButtonQ3A = QtWidgets.QRadioButton(self.groupBoxEmotion1_4)
        self.radioButtonQ3A.setGeometry(QtCore.QRect(10, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonQ3A.setFont(font)
        self.radioButtonQ3A.setObjectName("radioButtonQ3A")
        self.radioButtonQ3B = QtWidgets.QRadioButton(self.groupBoxEmotion1_4)
        self.radioButtonQ3B.setGeometry(QtCore.QRect(240, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonQ3B.setFont(font)
        self.radioButtonQ3B.setObjectName("radioButtonQ3B")
        self.radioButtonQ3C = QtWidgets.QRadioButton(self.groupBoxEmotion1_4)
        self.radioButtonQ3C.setGeometry(QtCore.QRect(470, 30, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonQ3C.setFont(font)
        self.radioButtonQ3C.setObjectName("radioButtonQ3C")
        self.radioButtonQ3D = QtWidgets.QRadioButton(self.groupBoxEmotion1_4)
        self.radioButtonQ3D.setGeometry(QtCore.QRect(720, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonQ3D.setFont(font)
        self.radioButtonQ3D.setObjectName("radioButtonQ3D")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_8 = QtWidgets.QLabel(self.page_6)
        self.label_8.setGeometry(QtCore.QRect(230, 200, 501, 161))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_Points = QtWidgets.QLabel(self.page_6)
        self.label_Points.setGeometry(QtCore.QRect(450, 280, 201, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_Points.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.label_Points.setFont(font)
        self.label_Points.setObjectName("label_Points")
        self.label_10 = QtWidgets.QLabel(self.page_6)
        self.label_10.setGeometry(QtCore.QRect(230, 360, 341, 101))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_6)
        self.label_num = QtWidgets.QLabel(self.centralwidget)
        self.label_num.setGeometry(QtCore.QRect(950, 745, 49, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_num.setFont(font)
        self.label_num.setObjectName("label_num")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">Praca magisterska</span></p><p align=\"center\">Wykorzystanie sygnałów EEG w badaniu emocji</p><p align=\"center\">odbiorców przekazu reklamowego prezentowanego w formie video</p><p align=\"center\"><span style=\" font-weight:700;\">Eksperyment badawczy</span></p><p align=\"center\"><br/></p><p>Poniższy eksperyment badawczy jest przeprowadzany w ramach pracy dyplomowej,</p><p>a wszystkie zebrane w trakcie niego dane zostaną wykorzystane wyłącznie w celach badawczych.</p><p>Celem eksperymentu jest weryfikacja, jakie emocje budzą w potencjalnych klientach reklamy video.</p><p>Zadaniem uczestnika badania jest wskazanie, jakie emocje wzbudziła według niego dana reklama </p><p>oraz odpowiedź na pytania dotyczące obejrzanego materiału. <span style=\" font-weight:700;\">Filmy należy oglądać uważnie!</span></p><p><br/></p><p><span style=\" font-weight:700;\">Po kliknięciu przycisku &quot;Rozpocznij&quot; nastąpi etap kalibracji. Prosze się zrelaksować :)</span></p></body></html>"))
        self.btnBegin.setText(_translate("MainWindow", "Rozpocznij"))
        self.label.setText(_translate("MainWindow", "Relaks z zamkniętymi oczami"))
        self.label_2.setText(_translate("MainWindow", "Relaks z otwartymi oczami"))
        self.labelVideoNum_1.setText(_translate("MainWindow", "Film 1"))
        self.labelVideoNum_2.setText(_translate("MainWindow", "Film 1"))
        self.label_3.setText(_translate("MainWindow", "Pytanie nr 1"))
        self.label_4.setText(_translate("MainWindow", "Jakie emocje wywołała reklama?"))
        self.checkBoxHappy.setText(_translate("MainWindow", "radość"))
        self.checkBoxAngry.setText(_translate("MainWindow", "złość"))
        self.checkBoxSad.setText(_translate("MainWindow", "smutek"))
        self.checkBoxFear.setText(_translate("MainWindow", "strach"))
        self.checkBoxDisgust.setText(_translate("MainWindow", "wstręt"))
        self.checkBoxSuprised.setText(_translate("MainWindow", "zaskoczenie"))
        self.checkBoxExcited.setText(_translate("MainWindow", "podniecenie"))
        self.btnNext.setText(_translate("MainWindow", "Dalej"))
        self.label_6.setText(_translate("MainWindow", "Można wybrać więcej niż jedną odpowiedź."))
        self.btnNext_2.setText(_translate("MainWindow", "Dalej"))
        self.radioButtonQ1A.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonQ1B.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonQ1C.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonQ1D.setText(_translate("MainWindow", "RadioButton"))
        self.labelVideoNum_3.setText(_translate("MainWindow", "Film 1"))
        self.label_5.setText(_translate("MainWindow", "Pytanie nr 2"))
        self.label_q1.setText(_translate("MainWindow", "Pierwsze pytanie odnosnie reklamy"))
        self.label_7.setText(_translate("MainWindow", "Pytanie nr 3"))
        self.label_q2.setText(_translate("MainWindow", "Drugie pytanie odnosnie reklamy"))
        self.radioButtonQ2A.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonQ2B.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonQ2C.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonQ2D.setText(_translate("MainWindow", "RadioButton"))
        self.label_9.setText(_translate("MainWindow", "Pytanie nr 4"))
        self.label_q3.setText(_translate("MainWindow", "Trzecie pytanie odnosnie reklamy"))
        self.radioButtonQ3A.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonQ3B.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonQ3C.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonQ3D.setText(_translate("MainWindow", "RadioButton"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Dziękuję za udział w badaniu!</p><p>Uzyskałeś: </p></body></html>"))
        self.label_Points.setText(_translate("MainWindow", "0/10 pkt"))
        self.label_10.setText(_translate("MainWindow", "GRATULACJE !"))
        self.label_num.setText(_translate("MainWindow", "1/10"))
from PyQt5.QtMultimediaWidgets import QVideoWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
